# TCL File Generated by Component Editor 23.1
# Tue Jan 27 10:12:27 BRT 2026
# DO NOT MODIFY


# 
# my_peripheral "my_peripheral" v1.0
# equipe_04 2026.01.27.10:12:27
# faz algo ai
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module my_peripheral
# 
set_module_property DESCRIPTION "faz algo ai"
set_module_property NAME my_peripheral
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP grupo_04
set_module_property AUTHOR equipe_04
set_module_property DISPLAY_NAME my_peripheral
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file my_peripheral.vhd VHDL PATH ../TESTE_FROM_NIOS/my_peripheral.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock_sink_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset_sink_reset reset Input 1


# 
# connection point avalon_slave_1_1_1
# 
add_interface avalon_slave_1_1_1 avalon end
set_interface_property avalon_slave_1_1_1 addressUnits WORDS
set_interface_property avalon_slave_1_1_1 associatedClock clock_sink
set_interface_property avalon_slave_1_1_1 associatedReset reset_sink
set_interface_property avalon_slave_1_1_1 bitsPerSymbol 8
set_interface_property avalon_slave_1_1_1 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_1_1_1 burstcountUnits WORDS
set_interface_property avalon_slave_1_1_1 explicitAddressSpan 0
set_interface_property avalon_slave_1_1_1 holdTime 0
set_interface_property avalon_slave_1_1_1 linewrapBursts false
set_interface_property avalon_slave_1_1_1 maximumPendingReadTransactions 0
set_interface_property avalon_slave_1_1_1 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_1_1_1 readLatency 0
set_interface_property avalon_slave_1_1_1 readWaitTime 1
set_interface_property avalon_slave_1_1_1 setupTime 0
set_interface_property avalon_slave_1_1_1 timingUnits Cycles
set_interface_property avalon_slave_1_1_1 writeWaitTime 0
set_interface_property avalon_slave_1_1_1 ENABLED true
set_interface_property avalon_slave_1_1_1 EXPORT_OF ""
set_interface_property avalon_slave_1_1_1 PORT_NAME_MAP ""
set_interface_property avalon_slave_1_1_1 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_1_1_1 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_1_1_1 avalon_slave_write write Input 1
add_interface_port avalon_slave_1_1_1 avalon_slave_read read Input 1
add_interface_port avalon_slave_1_1_1 avalon_slave_1_writedata writedata Input 32
add_interface_port avalon_slave_1_1_1 avalon_slave_1_readdata readdata Output 32
add_interface_port avalon_slave_1_1_1 avalon_slave_1_1_1_address address Input 4
set_interface_assignment avalon_slave_1_1_1 address 0
set_interface_assignment avalon_slave_1_1_1 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_1_1_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_1_1_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_1_1_1 embeddedsw.configuration.isPrintableDevice 0
set_interface_assignment avalon_slave_1_1_1 read 0
set_interface_assignment avalon_slave_1_1_1 readdata 0
set_interface_assignment avalon_slave_1_1_1 write 0
set_interface_assignment avalon_slave_1_1_1 writedata 0

